// Exercise 04
// Create brand new ReactJS application with `create-react-app` command.
// Create masterminds application.
//A basic game of guessing a number based on various degrees of difficulty. The objective of the game is to guess a number that is randomly generated by the game engine. On each guess, the game will indicate (using a message and color) how close (or far) your guess is from the actual generated number. Upon guessing the correct number, one is presented with the option to play again.
//
// The game provides 3 difficulty level settings, namely, easy, medium, and hard. Based on the difficulty setting, the game engine will generate a random number that falls within a number range. For example:
//
// Easy - 0 -> 10
// Medium - 0 -> 100
// Difficult - 0 -> 1000

// https://user-images.githubusercontent.com/33935506/33792331-08cb733e-dca5-11e7-9c6d-84002eba6b6b.PNG
// https://user-images.githubusercontent.com/33935506/33792332-0901984c-dca5-11e7-8c97-723756e40467.PNG
// https://user-images.githubusercontent.com/33935506/33792333-0934eb70-dca5-11e7-9a1c-a36133646fb1.PNG
// https://user-images.githubusercontent.com/33935506/33792335-0970e008-dca5-11e7-918f-5bb6c3414538.PNG
// https://user-images.githubusercontent.com/33935506/33792336-09a7b236-dca5-11e7-89d7-50c4ccd1659c.PNG

// Try to use as much separated components as possible